# Generated by Django 3.0.8 on 2020-08-13 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.URLField(blank=True, help_text='URL to view the deployed result.', verbose_name='URL')),
                ('type', models.IntegerField(choices=[(0, 'Local'), (1, 'FTP'), (2, 'SSH')], verbose_name='Type')),
                ('host', models.CharField(blank=True, help_text='E.g. ssh.server.com', max_length=80, verbose_name='Host')),
                ('user', models.CharField(blank=True, max_length=80, verbose_name='User')),
                ('path', models.CharField(help_text='Please specify the target directory.', max_length=255, verbose_name='Path')),
                ('authtype', models.IntegerField(blank=True, choices=[(0, 'Password'), (1, 'Public Key')], null=True, verbose_name='Authentication type')),
                ('password', models.CharField(blank=True, max_length=80, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Deployment host',
                'verbose_name_plural': 'Deployment hosts',
            },
        ),
        migrations.CreateModel(
            name='ExternalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('url', models.URLField(verbose_name='URL')),
                ('path', models.CharField(help_text='Please specify the target path.', max_length=255, unique=True, verbose_name='Target path')),
            ],
            options={
                'verbose_name': 'External URL',
                'verbose_name_plural': 'External URLs',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('url', models.CharField(default='/', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('timestamp', models.CharField(max_length=32, verbose_name='Timestamp')),
                ('archive', models.FileField(blank=True, upload_to='statify/releases/', verbose_name='Archive')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
    ]
