# Generated by Django 3.0.8 on 2020-08-14 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthost',
            name='target_domain',
            field=models.CharField(default='www.example.com', help_text='Will be used to replace domains inside of absolute links (e.g. www.example.com)', max_length=50, verbose_name='Target domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='host',
            field=models.CharField(blank=True, help_text='e.g. ssh.server.com', max_length=80, verbose_name='Host'),
        ),
    ]
