# Generated by Django 3.0.8 on 2020-08-14 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0003_auto_20200814_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthost',
            name='chmod',
            field=models.IntegerField(blank=True, help_text='e.g. 775', max_length=80, null=True, verbose_name='CHMOD'),
        ),
        migrations.AddField(
            model_name='deploymenthost',
            name='ssh_key_path',
            field=models.CharField(blank=True, help_text='e.g. /home/user/.ssh/id_rsa', max_length=255, null=True, verbose_name='SSH key path'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='authtype',
            field=models.IntegerField(blank=True, choices=[(0, 'Password'), (1, 'Key')], null=True, verbose_name='Authentication type'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='host',
            field=models.CharField(blank=True, help_text='e.g. ssh.server.com', max_length=80, null=True, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='user',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='url',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('(^\\/[A-Za-z0-9\\-\\_\\%\\?\\&\\=]+)', 'URL must start with a leading slash (e.g. /en/)')], verbose_name='URL'),
        ),
    ]
