# Generated by Django 3.0.8 on 2020-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0004_auto_20200814_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymenthost',
            name='chmod',
            field=models.CharField(blank=True, help_text='e.g. u-rwx,o+rwx', max_length=80, null=True, verbose_name='chmod'),
        ),
    ]
