# Generated by Django 3.0.8 on 2020-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0005_auto_20200814_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthost',
            name='chown',
            field=models.CharField(blank=True, help_text='e.g. www-data:www-data', max_length=80, null=True, verbose_name='chown'),
        ),
    ]
