# Generated by Django 3.0.8 on 2020-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0006_deploymenthost_chown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymenthost',
            name='target_domain',
            field=models.CharField(help_text='Will be used to replace domains inside of absolute links (e.g. www.example.com)', max_length=255, verbose_name='Target domain'),
        ),
    ]
