# Generated by Django 3.0.8 on 2020-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0007_auto_20200814_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthost',
            name='target_scheme',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=255, verbose_name='Target scheme'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='target_domain',
            field=models.CharField(help_text='e.g. www.example.com', max_length=255, verbose_name='Target domain'),
        ),
    ]
