# Generated by Django 3.0.8 on 2020-08-22 08:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0008_auto_20200822_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymenthost',
            name='url',
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='target_domain',
            field=models.CharField(help_text='e.g. www.example.com', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^([a-z0-9.-]+|\\[[a-f0-9]*:[a-f0-9\\.:]+\\])(:\\d+)?$'), 'The domain name provided is not valid according to RFC 1034/1035.')], verbose_name='Target domain'),
        ),
    ]
