# Generated by Django 3.0.8 on 2020-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0009_auto_20200822_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymenthost',
            name='authtype',
            field=models.IntegerField(blank=True, choices=[('0', 'Password'), ('1', 'Key')], null=True, verbose_name='Authentication type'),
        ),
        migrations.AlterField(
            model_name='deploymenthost',
            name='type',
            field=models.IntegerField(choices=[('0', 'Local'), ('1', 'FTP'), ('2', 'SSH')], verbose_name='Type'),
        ),
    ]
